services:

  # Symfony Backend
  symfony:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: symfony
    volumes:
      - ./backend/Symfony:/var/www/symfony
    networks:
      - app-network

  # Vite-React Frontend
  vite-react:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vite_react
    volumes:
      - ./frontend/React:/app
      - /app/node_modules
    ports:
      - "5173:5173"  # Expose Vite dev server port
    environment:
      VITE_API_BASE_URL: http://symfony:9000  # Symfony backend URL
    networks:
      - app-network

# Docker volumes and networks
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge